src/br/com/cursojsf/model/BaseModel.java
package br.com.cursojsf.model;

/**
 * Define uma cidade de umestado da federacao.
 * 
 * @author Fabio Barros
 */
public class BaseModel {
	/**
	 * Identificador da cidade.
	 */
	private Long id;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		return 31 * 1 + ((id == null) ? 0 : id.hashCode());
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BaseModel other = (BaseModel) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}

src/br/com/cursojsf/model/Cep.java
package br.com.cursojsf.model;
public class Cep {

  private String regiao;
  private String sufixo;

  public Cep() {
  }

  public Cep(String regiao, String sufixo) {
    this.regiao = regiao;
    this.sufixo = sufixo;
  }

  @Override
  public String toString() {
    return regiao + "-" + sufixo;
  }

  public String getRegiao() {
    return regiao;
  }

  public void setRegiao(String regiao) {
    this.regiao = regiao;
  }

  public String getSufixo() {
    return sufixo;
  }

  public void setSufixo(String sufixo) {
    this.sufixo = sufixo;
  }
}

src/br/com/cursojsf/model/Usuario.java
package br.com.cursojsf.model;

import java.io.Serializable;
import java.util.Date;

public class Usuario extends BaseModel implements Serializable {

	/**
	 * serialVersionUID.
	 */
	private static final long serialVersionUID = -3064306490724801147L;

	/**
	 * Nome reduzido do usuario.
	 */
	private String nomeReduzido;

	/**
	 * Nome completo do usuario.
	 */
	private String nomeCompleto;

	/**
	 * Email do usuario.
	 */
	private String email;

	/**
	 * Senha
	 */
	private String senha;

	/**
	 * CPF do usuario.
	 */
	private String cpf;

	/**
	 * Data de nascimento.
	 */
	private Date dataNascimento;

	private Cep cep;


	public String getNomeReduzido() {
		return nomeReduzido;
	}

	public void setNomeReduzido(String nomeReduzido) {
		this.nomeReduzido = nomeReduzido;
	}

	public String getNomeCompleto() {
		return nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}
	
	public Cep getCep() {
		return cep;
	}

	public void setCep(Cep cep) {
		this.cep = cep;
	}

	public Usuario() {
		super();
	}

	public Usuario(Long id) {
		this();
		setId(id);
	}

}

src/br/com/cursojsf/managedbean/JogoDaVelhaBean.java
package br.com.cursojsf.managedbean;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.cursojsf.business.JogoDaVelhaService;

@Named
@ViewScoped
public class JogoDaVelhaBean implements Serializable {

	private static final long serialVersionUID = 1L;
	@Inject
	protected JogoDaVelhaService service;

	public void novoJogo() {
		service.iniciaNovoJogo();
	}

	public boolean desabilitaCampo(String valorCampo) {
		return !"".equals(valorCampo) || service.isJogoFinalizado() || service.isJogoNaoIniciado()
				|| service.isJogoEmpatado();
	}

	public void marca(int position) {
		service.marcaJogada(position);
	}

	public List<String> getCampo() {
		return service.getCampo();
	}

	public boolean isJogoIniciado() {
		return service.isJogoIniciado();
	}

	public boolean isJogoFinalizado() {
		return service.isJogoFinalizado();
	}

	public boolean isJogoEmpatado() {
		return service.isJogoEmpatado();
	}

	public JogoDaVelhaService.Jogador getJogadorDaVez() {
		return service.getJogadorDaVez();
	}

	public JogoDaVelhaService.Jogador getJogador1() {
		return service.getJogador1();
	}

	public JogoDaVelhaService.Jogador getJogador2() {
		return service.getJogador2();
	}

}

src/br/com/cursojsf/managedbean/UsuarioBean.java
package br.com.cursojsf.managedbean;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.com.cursojsf.business.UsuarioBusiness;
import br.com.cursojsf.model.Usuario;

@ManagedBean
@RequestScoped
public class UsuarioBean {
	/** Referencia para a camada de regras de negocio */
	@ManagedProperty("#{usuarioBusiness}")
	private UsuarioBusiness usuarioBusiness;

	/** Usuario a serusado no form. */
	private Usuario usuario = new Usuario();

	public UsuarioBusiness getUsuarioBusiness() {
		return usuarioBusiness;
	}

	public void setUsuarioBusiness(UsuarioBusiness usuarioBusiness) {
		this.usuarioBusiness = usuarioBusiness;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public List<Usuario> getListaUsuarios() {
		return usuarioBusiness.selecionarTodos();
	}

	public String novo() {
		usuario = new Usuario();
		return "usuariosEditar";
	}

	public String salvar() {
		usuarioBusiness.salvarUsuario(usuario);
		return "usuarios";
	}

	public String excluir() {
		usuarioBusiness.excluirUsuario(usuario);
		return "usuarios";
	}
	
    public void exibir() {
        usuario = usuarioBusiness.selecionar(usuario);
    }
}

WebContent/WEB-INF/templates/padrao.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"       
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>
        <h:outputText value=": #{msg['application.name']} - #{msg['application.version']} : "/>
        <ui:insert name="title" />
    </title>
    <h:outputStylesheet name="css/styles.css"/>
</h:head>
<h:body>
    <div style="font-weight: bold;">
        <h:graphicImage value="#{resource['img:icon_java.gif']}"/>
        <ui:insert name="title" />
    </div>
    <hr />
    <ui:insert name="body" />
</h:body>
</html>

WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/padrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">#{msg['page.index.title']}</ui:define>
    <ui:define name="body">
	    <h:form>
	        <h:commandLink action="usuarios?faces-redirect=true"
	        	value="#{msg['page.usuarios.title']}" /><br/>
	        <h:commandLink action="jogo?faces-redirect=true"
	        	value="#{msg['page.jogo.title']}" /><br/>        	
	        <h:commandButton action="logout?faces-redirect=true"
	        	value="#{msg['page.logout.title']}" />
	    </h:form>    
    </ui:define>

</ui:composition>

WebContent/jogo.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<ui:decorate template="template.xhtml">
	<ui:define name="centro">
		<ui:param name="jogoDaVelhaBean" value="#{jogoDaVelhaBean}" />
		<style>
		.ui-widget{
			font-family: cursive;		
		}
		.cell-block {
			width: 100px;
			height: 80px;
			display: inline-block;
			padding: 0;
			margin: 0;
			float: left;
			text-align: center;
		}
		
		.top-left, .top-right {
			border-bottom: 1px solid black;
		}
		
		.top-center {
			border-bottom: 1px solid black;
			border-left: 1px solid black;
			border-right: 1px solid black;
		}
		
		.bottom-center {
			border-left: 1px solid black;
			border-right: 1px solid black;
		}
		
		.gamePosition {
			width: 100%;
			height: 100%;
			display: block;
			font-size: 50px;
			margin-top: 10px;
		}
		
		#controleJogo{
			width: 200px;
			table-layout:fixed;
		}
		
		#controleJogo th, #controleJogo td{
			
		}
		
		#controleJogo td{
			text-align: left;
			overflow: hidden;
		}
		
		#log{
			background-color: Gainsboro;
			width: auto;
			height: 90px;
			text-align: left;
			font-size: 10px;
			font-family: sans-serif;
			padding: 10px;
		}
</style>
		<h:form>
			<h2>Jogo da Velha</h2>
			<p:panelGrid columns="2" id="jogo">
				<h:panelGroup id="controleJogo">
						
						<table id="controleJogo">
							<col width="75px" />
    						<col width="75px" />
							<tr>
								<td colspan="2">
									<h3>
										<h:outputText value="Nome do jogadores: " />
									</h3>
								</td>								
							</tr>
							<tr>
								<td style="width: 75px;">
									<h:outputLabel value="Jogador O: " />														
								</td>
								<td>
									<p:inputText value="#{jogoDaVelhaBean.jogador1.nome}" style="width: 95px;"></p:inputText>
								</td>
							</tr>
							<tr>
								<td style="width: 75px;">
									<h:outputLabel value="Jogador X: " />
							
								</td>
								<td>
									<p:inputText value="#{jogoDaVelhaBean.jogador2.nome}" style="width: 95px;"></p:inputText>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<p:commandButton action="#{jogoDaVelhaBean.novoJogo}"
									value="Novo/Reiniciar Jogo" update="panelJogo" style="width: 100%; margin: 5px 0; padding: 5px 0;" />
									
								</td>
								
							</tr>
							<tr>
								<td colspan="2"><hr /></td>
							</tr>
							<tr>
								<td colspan="2">
									<div id="log">
										<i>instruções: </i>
										<h:outputText value="É a vez do jogador '#{jogoDaVelhaBean.jogadorDaVez.nome}'"
										rendered="#{jogoDaVelhaBean.jogoIniciado}" />
										<h:outputText value="Fim de jogo, vencedor é '#{jogoDaVelhaBean.jogadorDaVez.nome}'"
										rendered="#{jogoDaVelhaBean.jogoFinalizado}" />
										<h:outputText value="Fim de jogo, empate, inicie um novo jogo."
										rendered="#{jogoDaVelhaBean.jogoEmpatado}" />	
									
									</div>																
								</td>
							</tr>
						</table>
										
				</h:panelGroup>
				<h:panelGroup id="panelJogo">
					<div>
						<div class="cell-block top-left">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(0)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[0])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[0]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block top-center">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(1)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[1])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[1]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block top-right">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(2)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[2])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[2]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
					</div>
					<div>
						<div class="cell-block top-left">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(3)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[3])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[3]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block top-center">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(4)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[4])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[4]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block top-right">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(5)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[5])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[5]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
					</div>
					<div>
						<div class="cell-block ">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(6)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[6])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[6]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block bottom-center">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(7)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[7])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[7]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
						<div class="cell-block ">
							<h:commandLink styleClass="gamePosition"
								action="#{jogoDaVelhaBean.marca(8)}"
								disabled="#{jogoDaVelhaBean.desabilitaCampo(jogoDaVelhaBean.campo[8])}">
								<h:outputText value="#{jogoDaVelhaBean.campo[8]}" />
								<p:ajax update="jogo" />
							</h:commandLink>
						</div>
					</div>
					<div style="clear: both; height: 20px; width: 100%"></div>
				</h:panelGroup>
			</p:panelGrid>
		</h:form>
	</ui:define>
</ui:decorate>
</html>

WebContent/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">    
<h:head><title><h:outputText value="#{msg['page.login.title']}" /></title></h:head>
<h:body>
    <div align="center">
        <p:panel header="#{msg['page.login.title']}">
	        <h:form id="loginForm">
	            <h:message for="loginForm" errorStyle="color: red;" />    
	            <h:panelGrid columns="3">
	                <h:outputLabel for="cpfInput" 
	                    value="#{msg['page.login.label.cpf']}:" />
	                <p:inputText id="cpfInput" value="#{loginBean.cpf}" 
	                    maxlength="11" size="12" required="true" />
	                <h:message for="cpfInput" errorStyle="color: red;" />
	                <h:outputLabel for="senhaInput"
	                    value="#{msg['page.login.label.senha']}:" />  
	                <p:password id="senhaInput" value="#{loginBean.senha}"
	                    maxlength="11" size="12" required="true" />
	                <h:message for="senhaInput" errorStyle="color: red;" />
	            </h:panelGrid>
	            <p:commandButton action="#{loginBean.autenticar}"
	                value="#{msg['page.login.label.entrar']}"
	                ajax="false" />
	        </h:form>
        </p:panel>
    </div>
</h:body>
</html>

WebContent/logout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/padrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">#{msg['page.logout.title']}</ui:define>
    <ui:define name="body">
	    <h:outputText value="#{msg['page.logout.mensagem']}" />
	    <h:form>
	        <h:commandLink value="#{msg['page.index.title']}"
	            action="index?faces-redirect=true" />
	    </h:form>
    </ui:define>

</ui:composition>

WebContent/template.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Jogo da Velha</title>
	<style type="text/css">
body {
	background-color: #eeeeee;
	font-size: 12px
}
</style>
</h:head>
<h:body>
	<div align="center">
		<p:layout>

			<p:layoutUnit position="center">
				<p:messages id="messages" autoUpdate="true" closable="true" />
				<ui:insert name="centro">

				</ui:insert>
			</p:layoutUnit>

		</p:layout>
	</div>
</h:body>
</html>

WebContent/usuarios.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/padrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">#{msg['page.usuarios.title']}</ui:define>
    <ui:define name="body">
		<h:form>
			<h:dataTable value="#{usuarioBean.listaUsuarios}" var="usuario"
				border="1" cellspacing="0" cellpadding="2">
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['page.usuarios.label.cpf']}" />
					</f:facet>
					<h:commandLink action="usuariosEditar">
						<h:outputText value="#{usuario.cpf}"
							converter="converters.CpfConverter" />
						<f:setPropertyActionListener target="#{usuarioBean.usuario}"
							value="#{usuario}" />
					</h:commandLink>
				</h:column>
	
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['page.usuarios.label.nomeReduzido']}" />
					</f:facet>
					<h:outputText value="#{usuario.nomeReduzido}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['page.usuarios.label.email']}" />
					</f:facet>
					<h:outputLink value="mailto:#{usuario.email}">
						<h:outputText value="#{usuario.email}" />
					</h:outputLink>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['page.usuarios.label.dataNascimento']}" />
					</f:facet>
					<h:outputText value="#{usuario.dataNascimento}">
						<f:convertDateTime pattern="dd/MM/yyyy" />
					</h:outputText>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['page.usuarios.label.cep']}" />
					</f:facet>
					<h:commandLink action="usuariosEditar">
						<h:outputText value="#{usuario.cep}"
							converter="converters.CepConverter" />
						<f:setPropertyActionListener target="#{usuarioBean.cep}"
							value="#{cep}" />
					</h:commandLink>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						<h:outputText value="#{msg['commons.excluir']}" />
					</f:facet>
					<h:commandButton action="#{usuarioBean.excluir}"
						value="#{msg['commons.excluir']}">
						<f:setPropertyActionListener target="#{usuarioBean.usuario}"
							value="#{usuario}" />
					</h:commandButton>
				</h:column>
		        <h:column>
		            <f:facet name="header">
		                <h:outputText value="#{msg['commons.exibir']}" />
		            </f:facet>
		            <h:button outcome="usuariosExibir"
		                value="#{msg['commons.exibir']}">
		                <f:param name="id" value="#{usuario.id}" />
		            </h:button>
		        </h:column>
			</h:dataTable>
			<hr />
			<h:commandButton action="#{usuarioBean.novo}"
				value="#{msg['commons.novo']}" />
			<h:commandButton action="index" value="#{msg['commons.voltar']}" />
		</h:form>
    </ui:define>

</ui:composition>

WebContent/usuariosEditar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/padrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">#{msg['page.usuariosEditar.title']}</ui:define>
    <ui:define name="body">
		<h:messages globalOnly="true" errorStyle="color:red" />
		<h:form id="usuarioForm">
			<h:inputHidden value="#{usuarioBean.usuario.id}" />
			<h:panelGrid columns="3">
				<h:outputLabel for="idInput"
					value="#{msg['page.usuarios.label.id']}:" />
				<h:inputText id="idInput" value="#{usuarioBean.usuario.id}"
					disabled="true" />
				<h:panelGroup />
	
				<h:outputLabel for="cpfInput"
					value="#{msg['page.usuarios.label.cpf']}:" />
				<h:inputText id="cpfInput" required="true"
					value="#{usuarioBean.usuario.cpf}"
					converter="converters.CpfConverter">
					<f:validator validatorId="validators.CpfValidator" />
				</h:inputText>
				<h:message for="cpfInput" />
	
				<h:outputLabel for="nomeReduzidoInput"
					value="#{msg['page.usuarios.label.nomeReduzido']}:" />
				<h:inputText id="nomeReduzidoInput" required="true"
					value="#{usuarioBean.usuario.nomeReduzido}">
					<f:validateLength minimum="3" />
				</h:inputText>
				<h:message for="nomeReduzidoInput" />
	
				<h:outputLabel for="nomeCompletoInput"
					value="#{msg['page.usuarios.label.nomeCompleto']}:" />
				<h:inputTextarea id="nomeCompletoInput"
					value="#{usuarioBean.usuario.nomeCompleto}" rows="5" cols="20" />
				<h:message for="nomeCompletoInput" />
	
				<h:outputLabel for="dataNascimentoInput"
					value="#{msg['page.usuarios.label.dataNascimento']}:" />
				<h:inputText id="dataNascimentoInput" value="#{usuarioBean.usuario.dataNascimento}">
					<f:convertDateTime pattern="dd/MM/yyyy" />
				</h:inputText>
				<h:message for="dataNascimentoInput" />
	
				<h:outputLabel for="emailInput"
					value="#{msg['page.usuarios.label.email']}:" />
				<h:inputText id="emailInput" required="true" 
					value="#{usuarioBean.usuario.email}" />
				<h:message for="emailInput" />
	
				<h:outputLabel for="senhaInput"
					value="#{msg['page.usuarios.label.senha']}:" />
				<h:inputText id="senhaInput" required="true" 
					value="#{usuarioBean.usuario.senha}" />
				<h:message for="senhaInput" />
				
				<h:outputLabel for="cpfInput"
					value="#{msg['page.usuarios.label.cep']}:" />
				<h:inputText id="cepInput" required="true"
					value="#{usuarioBean.usuario.cep}"
					converter="converters.CepConverter">
					<f:validator validatorId="validators.CepValidator" />
				</h:inputText>
				<h:message for="cepInput" />
				
			</h:panelGrid>
			<hr />
			<h:commandButton action="#{usuarioBean.salvar}"
				value="#{msg['commons.salvar']}" />
			<h:commandButton action="usuarios" 
				value="#{msg['commons.voltar']}"
				immediate="true" />
		</h:form>
    </ui:define>

</ui:composition>

WebContent/usuariosExibir.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/padrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">#{msg['page.usuarios.title']}</ui:define>
    <ui:define name="body">
	    <f:metadata>
	        <f:viewParam name="id" value="#{usuarioBean.usuario.id}" />
	        <f:event type="preRenderView" listener="#{usuarioBean.exibir}" />
	    </f:metadata>
	
	    <h:panelGrid columns="2">
	        <h:outputText value="#{msg['page.usuarios.label.id']}:" />
	        <h:outputText value="#{usuarioBean.usuario.id}" />
	
	        <h:outputText value="#{msg['page.usuarios.label.cpf']}:" />
	        <h:outputText value="#{usuarioBean.usuario.cpf}">
	            <f:converter converterId="converters.CpfConverter" />
	        </h:outputText>
	                <h:outputText value="#{msg['page.usuarios.label.nomeReduzido']}:" />
	        <h:outputText value="#{usuarioBean.usuario.nomeReduzido}" />
	
	        <h:outputText value="#{msg['page.usuarios.label.nomeCompleto']}:" />
	        <h:outputText value="#{usuarioBean.usuario.nomeCompleto}" />
	
	        <h:outputText value="#{msg['page.usuarios.label.email']}:" />
	        <h:outputText value="#{usuarioBean.usuario.email}" />
	
	        <h:outputText value="#{msg['page.usuarios.label.dataNascimento']}:" />
	        <h:outputText value="#{usuarioBean.usuario.dataNascimento}">
	            <f:convertDateTime pattern="dd/MM/yyyy" />
	        </h:outputText>
	    </h:panelGrid>
	    <hr />
	    <h:button outcome="usuarios" value="#{msg['commons.voltar']}" />
    </ui:define>

</ui:composition>